# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.runs/synth_1/rete_neurale.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a50ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.cache/wt [current_project]
set_property parent.project_path D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys-a7-50t:part0:1.2 [current_project]
set_property ip_output_repo d:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/1bit_register.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/output/mult/32bit_shift_register.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/hidden/mult/9bit_register.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/hidden/mult/control_unit.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/hidden/mult/counter_9.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/hidden/mult/adder_sub.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/hidden/mult/Booth_multiplier.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/output/mult/control_unit_32b.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/output/mult/counter_32.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/adder_64_test.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/output/mult/Booth_multiplier_32.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/type_package.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/ROM.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/type_package_output.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/ROM_output.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/ReLU.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/adder_sub_32.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/output/adder_sub_64.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/output/counter_10.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/hidden/mult/full_adder.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/hidden_layer.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/hidden/uc_neurone_hidden.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/mux_16_1.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/mux_2_1.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/register_neurone.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/hidden/hidden_neuron.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/mux_16_1_output.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/output/output_layer.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/output/uc_neurone_output.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/output/output_neuron.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/hidden/mult/ripple_carry.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/ripple_carry_32.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/neuroni/output/ripple_carry_64.vhd
  D:/Xilinx/Progetti_Xilinx/12_rete_neurale/12_rete_neurale.srcs/sources_1/new/rete_neurale.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top rete_neurale -part xc7a50ticsg324-1L -incremental_mode off
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rete_neurale.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rete_neurale_utilization_synth.rpt -pb rete_neurale_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
